#!/bin/bash -e
# regenerate syncthing secrets by removing default config and restarting
# (syncthing will auto regenerate required files)

CONF_DIR=/home/syncthing/.config/syncthing

systemctl enable syncthing@syncthing.service
systemctl stop syncthing@syncthing.service

# create backups, just in case...
FILES="config.xml cert.pem cert.key https-cert.pem https-key.pem csrftokens.txt"
for file in ${FILES}; do
    file=${CONF_DIR}/${file}
    if [[ -f ${file} ]]; then
        mv ${file} ${file}.bak
    fi
done

systemctl start syncthing@syncthing.service

# Set up TurnKey default config

CONF=${CONF_DIR}/config.xml

# wait until conf file is present
while true; do
    if [[ -f ${CONF} ]]; then
        break
    else
        sleep 1
    fi
done

# remove default user(s) & password(s) (shouldn't be any with clean conf, but for good measure)
sed -i '\|<user>.*|d' $CONF
sed -i '\|<password>.*|d' $CONF

# add new default user 'syncthing' with (temporary) mcookie password (adjusted by inithook)
PASS=$(mcookie)$(mcookie)
sed -i '\|<address>[0-9].*</address>|a \\t<user>syncthing</user>' $CONF
# note extra \ redq for tab when wrapped in double quotes
sed -i "\|<user>syncthing</user>|a \\\t<password>${PASS}</password>" $CONF

# allow access from anywhere
sed -i 's|<address>[0-9].*</address>|<address>0.0.0.0:8384</address>|g' $CONF
# force TLS (aka SSL)
sed -i 's|tls="false"|tls="true"|g' $CONF
